Create db 1
pelicsilla/SnowWhite_db pull request #1
Opened 2024-11-05 21:19 UTC by pelicsilla

2024-11-06 15:10 UTC, marci1999 requested changes

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +def load_csv_data(file_path) -> pd.DataFrame:
hiányzó típus annotáció a "file_path" paraméterhez

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    datum_columns = df['Datum'].str.split('.', expand=True)
használat nélkül deklarált változó

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    df['gyemant'] = df['gyemant'].replace(',', '.', regex=True)
Felesleges regex paraméter

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    df['gyemant'] = df['gyemant'].astype(float).astype(int)
Felesleges kétszeres típuskonverzió

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    # Return df, further cleaning is not necessary
felesleges komment

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +def create_database(db_path, table_query):
hiányzó típus annotációk

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    cursor.execute("DROP TABLE IF EXISTS termeles")
Táblanév hardcoded, célszerű lenne paraméterben megadni

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    conn.close()
Nincs kivételkezelés az adatbázis kapcsolat lezárására

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +def insert_data_to_database(db_path: str, df):
hiányzó típus annotáció a "df" paraméterhez

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    for index, row in df.iterrows():
Felesleges változó deklaráció "index"

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    conn.commit()
Adatbázis commit hiányzik kivételkezelés nélkül

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +def main(csv_file_path: str, db_file_path: str):
Felesleges típus annotáció main funkcióban

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    """
nincs külön funkció a tábla létrehozásának kezelésére

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +    insert_data_to_database(db_file_path, df)
nincs visszajelzés az adatok sikeres beillesztéséről

2024-11-06 15:10 UTC, marci1999 commented on create_db.py
> +main('Hofeherke.csv', 'termeles.db')
fájlnevek hardcoded, célszerű paraméterben megadni

2024-11-07 17:59 UTC, pelicsilla commented on create_db.py
> +def load_csv_data(file_path) -> pd.DataFrame:
Added

2024-11-07 17:59 UTC, pelicsilla commented on create_db.py
> +    datum_columns = df['Datum'].str.split('.', expand=True)
Modified

2024-11-07 18:00 UTC, pelicsilla commented on create_db.py
> +    df['gyemant'] = df['gyemant'].replace(',', '.', regex=True)
Deleted

2024-11-07 18:00 UTC, pelicsilla commented on create_db.py
> +    df['gyemant'] = df['gyemant'].astype(float).astype(int)
Rewritten

2024-11-07 18:01 UTC, pelicsilla commented on create_db.py
> +    # Return df, further cleaning is not necessary
Deleted

2024-11-07 18:03 UTC, pelicsilla commented on create_db.py
> +    conn.commit()
Try-except-finally block is inserted to handle errors

2024-11-07 18:04 UTC, pelicsilla commented on create_db.py
> +def main(csv_file_path: str, db_file_path: str):
This part os code was refactored

2024-11-07 18:05 UTC, pelicsilla commented on create_db.py
> +    """
This part of code was refactored

2024-11-07 18:05 UTC, pelicsilla commented on create_db.py
> +main('Hofeherke.csv', 'termeles.db')
Hardcoded names were parametrised

2024-11-07 18:06 UTC, pelicsilla commented on create_db.py
> +    insert_data_to_database(db_file_path, df)
Inserted message about it

2024-11-07 18:08 UTC, pelicsilla commented on create_db.py
> +def create_database(db_path, table_query):
Type annotations were inserted

2024-11-07 18:08 UTC, pelicsilla commented on create_db.py
> +    cursor.execute("DROP TABLE IF EXISTS termeles")
Table name was parametrised

2024-11-07 18:08 UTC, pelicsilla commented on create_db.py
> +    conn.close()
Try-except-finally block was inserted

2024-11-07 18:09 UTC, pelicsilla commented on create_db.py
> +def insert_data_to_database(db_path: str, df):
Type annotation was inserted

2024-11-07 18:10 UTC, pelicsilla commented on create_db.py
> +    for index, row in df.iterrows():
"index" was replaced by "_"

2024-11-08 11:35 UTC, marci1999 approved these changes
mot már jó

2024-11-08 11:35 UTC, merged